
import './globals.css'
import Navbar from "@/components/Navbar"
import {Albert_Sans, Montserrat_Alternates} from 'next/font/google' 

const albertSan = Albert_Sans({
  subsets: ['latin'],
  display: 'swap'
})

const montserratAlternates = Montserrat_Alternates({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700']
})
export const metadata = {
  title: 'PrintForge',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar/>
      <body className={` ${albertSan.className} ${montserratAlternates.className}`}>{children}</body>
    </html>
  )
}
