
import './globals.css'
import Navbar from "@/components/Navbar"
export const metadata = {
  title: 'PrintForge',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar/>
      <body>{children}</body>
    </html>
  )
}
